---
apiVersion: v1
kind: Service
metadata:
  name: discuz-service
  namespace: dev
spec:
  selector:
    app: discuz
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
